; Script generated by the Inno Setup Script Wizard.
[Setup]
AppName=Gestao Clientes
AppVerName=Gestao Clientes para Windows Vista
OutputBaseFilename=Setup-WinVista
AppPublisher=Grupo DESAFIOAC
AppPublisherURL=http://www.DESAFIOAC.com.br/
AppSupportURL=http://www.DESAFIOAC.com.br/
AppUpdatesURL=http://www.DESAFIOAC.com.br/
UsePreviousAppDir=no
DefaultDirName=C:\DESAFIOAC
DisableDirPage=false
DefaultGroupName=Grupo DESAFIOAC
DisableProgramGroupPage=true
OutputDir=E:\Instalacao
SetupIconFile=E:\Imagens\NOTE05.ICO
Compression=lzma
SolidCompression=true
UserInfoPage=false
UninstallDisplayIcon={app}\DESAFIOAC.exe
UninstallDisplayName=Grupo DESAFIOAC
UsePreviousGroup=false
PrivilegesRequired=admin
InternalCompressLevel=normal
;MinVersion=0,6.0.6000
EnableDirDoesntExistWarning=true

[Languages]
Name: brazilianportuguese; MessagesFile: compiler:Languages\BrazilianPortuguese.isl

[Run]
;Filename: {app}\DESAFIOACUpdateOffLine; Flags: shellexec postinstall runascurrentuser runminimized hidewizard; StatusMsg: Atualizando Banco de Dados com o PostScrip.SQL; Description: Atualizar Objetos do Banco de Dados; WorkingDir: {app}; Components: Atualizacao

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}

[Files]
;aplicação
Source: E:\DESAFIOAC.exe; DestDir: {app}; Flags: ignoreversion; Components: Instalacao Atualizacao

;RPTs

;base de dados

;dependencias do VB e SQL
Source: E:\DEPENDENCIAS\craxddrt.dll; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\mail.ocx; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\MSCAL.OCX; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\MSCHRT20.OCX; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\sFTP.ocx; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\COMCTL32.OCX; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\RICHTX32.OCX; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\MSINET.OCX; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\MSWINSCK.OCX; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\MSCOMM32.OCX; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\comdlg32.ocx; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\MSMASK32.OCX; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\THREED32.OCX; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\ss32x25.ocx; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\mscomctl.ocx; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\MSCOMCT2.OCX; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\TABCTL32.OCX; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\MFC40.DLL; DestDir: {sys}; Flags: restartreplace uninsneveruninstall sharedfile regserver; Components: Instalacao
Source: E:\DEPENDENCIAS\mfc42.dll; DestDir: {sys}; Flags: restartreplace uninsneveruninstall sharedfile regserver; Components: Instalacao
Source: E:\DEPENDENCIAS\MSVCRT.DLL; DestDir: {sys}; Flags: restartreplace uninsneveruninstall sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\scrrun.dll; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\MyGasChave.dll; DestDir: {sys}; Flags: promptifolder sharedfile regserver; Components: Instalacao
Source: E:\DEPENDENCIAS\SQLDMO.dll; DestDir: {app}; Flags: promptifolder; Components: Instalacao
Source: E:\DEPENDENCIAS\COMCAT.DLL; DestDir: {sys}; Flags: restartreplace uninsneveruninstall sharedfile regserver; Components: Instalacao
Source: E:\DEPENDENCIAS\OLEPRO32.DLL; DestDir: {sys}; Flags: restartreplace uninsneveruninstall sharedfile regserver; Components: Instalacao
Source: E:\DEPENDENCIAS\MSVCRT40.DLL; DestDir: {sys}; Flags: restartreplace uninsneveruninstall sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\ASYCFILT.DLL; DestDir: {sys}; Flags: restartreplace uninsneveruninstall sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\OLEAUT32.DLL; DestDir: {sys}; Flags: restartreplace uninsneveruninstall sharedfile regserver; Components: Instalacao
Source: E:\DEPENDENCIAS\msvbvm60.dll; DestDir: {sys}; Flags: restartreplace uninsneveruninstall sharedfile regserver; Components: Instalacao
Source: E:\DEPENDENCIAS\msvcr71.dll; DestDir: {sys}; Flags: promptifolder sharedfile onlyifdoesntexist; Components: Instalacao
Source: E:\DEPENDENCIAS\implode.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\msxml.dll; DestDir: {sys}; Flags: promptifolder sharedfile regserver; Components: Instalacao
Source: E:\DEPENDENCIAS\msxml6.dll; DestDir: {sys}; Flags: promptifolder sharedfile regserver; Components: Instalacao
Source: E:\DEPENDENCIAS\msxml6r.dll; DestDir: {sys}; Flags: promptifolder sharedfile regserver; Components: Instalacao
Source: E:\DEPENDENCIAS\msstdfmt.dll; DestDir: {sys}; Flags: promptifolder sharedfile regserver; Components: Instalacao
Source: E:\DEPENDENCIAS\SYSINFO.OCX; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\azip32.dll; DestDir: {sys}; Flags: promptifolder sharedfile regserver; Components: Instalacao
Source: E:\DEPENDENCIAS\aunzip32.dll; DestDir: {sys}; Flags: promptifolder sharedfile regserver; Components: Instalacao

;embarque do Cristall ( nao aceita registração )
Source: E:\DEPENDENCIAS\crpe32.dll; DestDir: {sys}; Flags: promptifolder; Components: Instalacao
Source: E:\DEPENDENCIAS\p2bdao.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\p2ctdao.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\p2irdao.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\p2bbde.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\P2bbnd.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\sscsdk80.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\Crpaig80.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\crxf_pdf.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\crxf_rtf.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\pg32conv.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\u2dapp.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\u2ddisk.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\u2dmapi.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\u2dnotes.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\u2dpost.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\u2dvim.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\u2fwordw.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\u2fxls.dll; DestDir: {sys}; Flags: promptifolder sharedfile; Components: Instalacao

;embarque do Cristall ( aceita registração )
Source: E:\DEPENDENCIAS\crtslv.dll; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\Crystl32.OCX; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\exportmodeller.dll; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\craxddrt.dll; DestDir: {sys}; Flags: promptifolder regserver sharedfile; Components: Instalacao
Source: E:\DEPENDENCIAS\U2LBCP.DLL; DestDir: {sys}; Flags: promptifolder sharedfile regserver; Components: Instalacao

[Icons]
Name: {group}\Grupo DESAFIOAC; Filename: {app}\DESAFIOAC.exe
Name: {commondesktop}\Grupo DESAFIOAC; Filename: {app}\DESAFIOAC.exe; Tasks: desktopicon
Name: {group}\{cm:UninstallProgram, Grupo DESAFIOAC}; Filename: {uninstallexe}

[Components]
Name: Atualizacao; Description: Atualização dos Componentes Já Instalados; Flags: exclusive disablenouninstallwarning; Types: full; Languages: 
Name: Instalacao; Description: Instalação Completa dos Componentes; Flags: exclusive disablenouninstallwarning; Types: full; Languages: 

[Code]
// X64
function IsX64: Boolean;
begin
  //Result := Is64BitInstallMode and (ProcessorArchitecture = paX64);
  Result := ProcessorArchitecture = paX64;
end;

// IA64
function IsIA64: Boolean;
begin
  //Result := Is64BitInstallMode and (ProcessorArchitecture = paIA64);
  Result := ProcessorArchitecture = paIA64;
end;

function IsOtherArch: Boolean;
begin
  Result := not IsX64 and not IsIA64;
end;

function IsWindowsXP: Boolean;
var
  Version: TWindowsVersion;
  S: String;
begin
  GetWindowsVersionEx(Version);
  Result := Version.NTPlatform and (Version.Major = 5) and (Version.Minor = 1);
end;

function InitializeSetup(): Boolean;
begin
    if not IsOtherArch or IsWindowsXP then begin
        MsgBox('Este Programa requer Sistema Operacional Windows Vista ou Superior de 32 bits, processador com base em x86.'#13#13
            'Por favor utilizar SETUP correspondente ao seu Sistema Operacional para Instalar esta versão.'#13
            'e rode novamente este Setup.', mbInformation, MB_OK);
        result := false;

    end else
	begin

        result := true;
    end ;
end;
